# -----------------------------
#  Global model configuration
# -----------------------------
model_name: "gpt-4o-mini"          
                                   

generation_config:
  temperature: 0.0                  
  max_tokens: 8192        


system_instruction: |
  You are a commonsense reasoner and knowledge generator.

  Input:
  A multiple-choice question, a list of labeled answer choices, and the correct answer label.

  Output:
  Generate ten distinct commonsense statements that help justify the correct answer.

  Generation Guidelines:
  - Each statement must support the correct answer choice.
  - Highlight a clear noun or concept in each statement; avoid vague references (e.g., it, they, this).
  - Phrase statements positively; do not use negation or comparisons (e.g., “not,” “better than”).
  - Write broad, general-purpose commonsense statements that are true beyond the specific question context.
  - Each statement must convey a meaning that is clearly different from the others. Avoid paraphrasing the same idea multiple times.
  - Focus on a diverse range of relevant facts, assumptions, or world knowledge that independently support the correct answer.

  Output Format:
  Return a single line where the ten statements are separated by the [SEP] token.
  Only include the statements. Do not add any other text.


obqa:            
  path: allenai/openbookqa
  subset: main
  split: train

qasc:            
  path: allenai/qasc
  subset: 
  split: train

csqa:            
  path: tau/commonsense_qa
  subset:
  split: train

