# Generic settings
seed: 150

# Datasets
obqa:
    dataset_name: "obqa"
    dataset_path: "allenai/openbookqa"
    split: "test"
    subset: "main"
    max_samples: 1
    shuffle: false

obqa_fewshot:
    dataset_name: "obqa_fewshot"
    dataset_path: "data/obqa/data=obqa|fewshot_examples.csv"
    max_samples:
    shuffle: false


qasc:
    dataset_name: "qasc"
    dataset_path: "allenai/qasc"
    split: "validation"
    subset:
    max_samples:
    shuffle: false

qasc_fewshot:
    dataset_name: "qasc_fewshot"
    dataset_path: "data/qasc/data=qasc|fewshot_examples.csv"
    max_samples:
    shuffle: false


csqa:
    dataset_name: "csqa"
    dataset_path: "tau/commonsense_qa"
    split: "validation"
    subset:
    max_samples:
    shuffle: false

csqa_fewshot:
    dataset_name: "csqa_fewshot"
    dataset_path: "data/csqa/data=csqa|fewshot_examples.csv"
    max_samples:
    shuffle: false


# Retriever
retriever:
    model_name: "intfloat/e5-base-v2"
    



