# Generic settings
seed: 150

# Prompts settings
prompts:
    top_k_list: [1, 3, 5, 10, 20]

# Datasets
obqa:
    dataset_name: "obqa"
    dataset_path: "allenai/openbookqa"
    split: "test"
    subset: "main"
    max_samples:
    shuffle: true

obqa_fewshot:
    dataset_name: "obqa_fewshot"
    dataset_path: "data/obqa/fewshot_examples.csv"
    max_samples:
    shuffle: true


# Retriever
retriever:
    model_name: "intfloat/e5-base-v2"
    



