# Generic settings
seed: 150

# Datasets
obqa:
    dataset_name: "obqa"
    dataset_path: "allenai/openbookqa"
    split: "test"
    subset: "main"
    max_samples:
    shuffle: false

obqa_fewshot:
    dataset_name: "obqa_fewshot"
    dataset_path: "data/obqa/fewshot_examples.csv"
    max_samples:
    shuffle: false


# Retriever
retriever:
    model_name: "intfloat/e5-base-v2"
    



