# Generic settings
seed: 150

# Datasets
obqa:
    name: "obqa"
    path: "allenai/openbookqa"
    split: "train"
    subset: "main"
    max_samples: 1000
    shuffle: true

qasc:
    name: "qasc"
    path: "allenai/qasc"
    split: train
    subset:
    max_samples: 1000
    shuffle: true

csqa:
    name: "csqa"
    path: "tau/commonsense_qa"
    split: "train"
    subset:
    max_samples: 1000
    shuffle: true


obqa_fewshot:
    name: "obqa_fewshot"
    path: "data/obqa/data=obqa|fewshot_examples.csv"
    max_samples:
    shuffle: false

qasc_fewshot:
    name: "qasc_fewshot"
    path: "data/qasc/data=qasc|fewshot_examples.csv"
    max_samples:
    shuffle: false

csqa_fewshot:
    name: "csqa_fewshot"
    path: "data/csqa/data=csqa|fewshot_examples.csv"
    max_samples:
    shuffle: false

obqa_fscotk:
    name: "obqa_fewshot"
    path: "data/obqa/data=obqa|fscotk_examples.csv"
    max_samples:
    shuffle: false

qasc_fscotk:
    name: "qasc_fewshot"
    path: "data/qasc/data=qasc|fscotk_examples.csv"
    max_samples:
    shuffle: false

csqa_fscotk:
    name: "csqa_fewshot"
    path: "data/csqa/data=csqa|fscotk_examples.csv"
    max_samples:
    shuffle: false


# Retriever
retriever:
    model_name: "intfloat/e5-base-v2"
    



